MODEL = 'models'
MODEL_NAME = 'model_2'
MODEL_PATH = f'./{MODEL}/{MODEL_NAME}'

DATASET = 'modelnet10.npz'
LEARNING_RATE = 1e-4
LEARNING_RATE_CLASSIFIER = 1e-3
BUFFER_SIZE = 5000
BATCH_SIZE = 32
Z_DIM = 100
EPOCHS = 3
NUM_IMAGES_TO_GENERATE = 4
N_CLASSES = 10